// gui/frontend/src/App.svelte
<script lang="ts">
  import './app.css';
  import { Events } from "@wailsio/runtime";
  import {GreetService} from "../bindings/gui";

  let name: string = $state('');
  let result: string = $state('Please enter your name below 👇');
  let time: string = $state('Listening for Time event...');

  const doGreet = () => {
    let localName = name;

    if (!localName) {
      localName = 'anonymous';
    }

    GreetService.Greet(localName).then((resultValue: string) => {
      result = resultValue;
    }).catch((err: any) => {
      console.log(err);
    });
  };

  Events.On('time', (timeValue: any) => {
    time = timeValue.data;
  });
</script>

<div class="container">
  <div>
    <span data-wml-openURL="https://wails.io">
      <img src="/wails.png" class="logo" alt="Wails logo"/>
    </span>
    <span data-wml-openURL="https://svelte.dev">
      <img src="/svelte.svg" class="logo svelte" alt="Svelte logo"/>
    </span>
  </div>
  <h1>Wails + Svelte</h1>
  <div class="result">{result}</div>
  <div class="card">
    <div class="input-box">
      <input class="input" bind:value={name} type="text" autocomplete="off"/>
      <button class="btn" onclick={doGreet}>Greet</button>
    </div>
  </div>
  <div class="footer">
    <div><p>Click on the Wails logo to learn more</p></div>
    <div><p>{time}</p></div>
  </div>
</div>

<style>
  /* Put your standard CSS here */
</style>

// gui/frontend/src/App.tsx
import { useEffect, useState } from 'react';
import { Events, WML } from '@wailsio/runtime';
import { GreetService } from '../bindings/gui';

function App() {
    const [name, setName] = useState<string>('');
    const [result, setResult] = useState<string>('Please enter your name below 👇');
    const [time, setTime] = useState<string>('Listening for Time event...');

    const doGreet = () => {
        let localName = name;
        if (!localName) {
            localName = 'anonymous';
        }
        GreetService.Greet(localName)
            .then((resultValue: string) => {
                setResult(resultValue);
            })
            .catch((err: any) => {
                console.log(err);
            });
    };

    useEffect(() => {
        Events.On('time', (timeValue: any) => {
            setTime(timeValue.data);
        });
        // Reload WML so it picks up the wml tags
        WML.Reload();
    }, []);

    return (
        <div className="container">
            <div>
                <a data-wml-openURL="https://wails.io">
                    <img src="/wails.png" className="logo" alt="Wails logo" />
                </a>
                <a data-wml-openURL="https://reactjs.org">
                    <img src="/react.svg" className="logo react" alt="React logo" />
                </a>
            </div>
            <h1>Wails + React</h1>
            <div className="result">{result}</div>
            <div className="card">
                <div className="input-box">
                    <input
                        className="input"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        type="text"
                        autoComplete="off"
                    />
                    <button className="btn" onClick={doGreet}>
                        Greet
                    </button>
                </div>
            </div>
            <div className="footer">
                <div>
                    <p>Click on the Wails logo to learn more</p>
                </div>
                <div>
                    <p>{time}</p>
                </div>
            </div>
        </div>
    );
}

export default App;
