// gui/frontend/src/components/Navbar.svelte
<script lang="ts">
    import { Navbar, NavBrand, NavLi, NavUl } from 'flowbite-svelte';
</script>

<Navbar class="bg-primary-100 dark:bg-primary-700 py-0" fluid={false}>
    <NavBrand>
        <span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white">Open Photo AI</span>
    </NavBrand>

    <NavUl ulClass="py-2">
        <NavLi href="/">Home</NavLi>
        <NavLi href="/about">About</NavLi>
        <NavLi href="/docs/components/navbar">Navbar</NavLi>
        <NavLi href="/pricing">Pricing</NavLi>
        <NavLi href="/contact">Contact</NavLi>
    </NavUl>
</Navbar>

// gui/frontend/src/components/Navbar.tsx
import { NavbarBrand, NavbarCollapse, NavbarLink, Navbar as Navigation } from 'flowbite-react';

type NavbarProps = {
    className?: string;
};

export const Navbar = ({ className = '' }: NavbarProps) => {
    return (
        <Navigation fluid={true} className={`dark:bg-[#212121] ${className}`}>
            <NavbarBrand>
                <span className="self-center whitespace-nowrap text-lg font-semibold dark:text-[#b0b0b0]">
                    Open Photo AI
                </span>
            </NavbarBrand>

            <NavbarCollapse>
                <NavbarLink href="/">Home</NavbarLink>
                <NavbarLink href="/about">About</NavbarLink>
                <NavbarLink href="/docs/components/navbar">Navbar</NavbarLink>
                <NavbarLink href="/pricing">Pricing</NavbarLink>
                <NavbarLink href="/contact">Contact</NavbarLink>
            </NavbarCollapse>
        </Navigation>
    );
};
